// Code generated by protoc-gen-go.
// source: client.proto
// DO NOT EDIT!

package upax_go

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type UpaxClientMsg_Cmd int32

const (
	UpaxClientMsg_KeepAlive UpaxClientMsg_Cmd = 3
	UpaxClientMsg_Ack       UpaxClientMsg_Cmd = 4
	UpaxClientMsg_Error     UpaxClientMsg_Cmd = 5
	UpaxClientMsg_Get       UpaxClientMsg_Cmd = 6
	UpaxClientMsg_Put       UpaxClientMsg_Cmd = 7
	UpaxClientMsg_IHave     UpaxClientMsg_Cmd = 8
	UpaxClientMsg_Bye       UpaxClientMsg_Cmd = 10
)

var UpaxClientMsg_Cmd_name = map[int32]string{
	3:  "KeepAlive",
	4:  "Ack",
	5:  "Error",
	6:  "Get",
	7:  "Put",
	8:  "IHave",
	10: "Bye",
}
var UpaxClientMsg_Cmd_value = map[string]int32{
	"KeepAlive": 3,
	"Ack":       4,
	"Error":     5,
	"Get":       6,
	"Put":       7,
	"IHave":     8,
	"Bye":       10,
}

func (x UpaxClientMsg_Cmd) Enum() *UpaxClientMsg_Cmd {
	p := new(UpaxClientMsg_Cmd)
	*p = x
	return p
}
func (x UpaxClientMsg_Cmd) String() string {
	return proto.EnumName(UpaxClientMsg_Cmd_name, int32(x))
}
func (x UpaxClientMsg_Cmd) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *UpaxClientMsg_Cmd) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UpaxClientMsg_Cmd_value, data, "UpaxClientMsg_Cmd")
	if err != nil {
		return err
	}
	*x = UpaxClientMsg_Cmd(value)
	return nil
}

type UpaxClientMsg struct {
	Op               *UpaxClientMsg_Cmd `protobuf:"varint,1,opt,enum=upax_go.UpaxClientMsg_Cmd" json:"Op,omitempty"`
	MsgN             *uint64            `protobuf:"varint,2,opt" json:"MsgN,omitempty"`
	ID               []byte             `protobuf:"bytes,3,opt" json:"ID,omitempty"`
	Salt             []byte             `protobuf:"bytes,4,opt" json:"Salt,omitempty"`
	Sig              []byte             `protobuf:"bytes,5,opt" json:"Sig,omitempty"`
	YourSeqN         *uint64            `protobuf:"varint,6,opt" json:"YourSeqN,omitempty"`
	YourID           []byte             `protobuf:"bytes,7,opt" json:"YourID,omitempty"`
	ErrCode          *uint64            `protobuf:"varint,8,opt" json:"ErrCode,omitempty"`
	ErrDesc          *string            `protobuf:"bytes,9,opt" json:"ErrDesc,omitempty"`
	Hash             []byte             `protobuf:"bytes,10,opt" json:"Hash,omitempty"`
	Payload          []byte             `protobuf:"bytes,11,opt" json:"Payload,omitempty"`
	Index            *int64             `protobuf:"varint,32,opt" json:"Index,omitempty"`
	Timestamp        *int64             `protobuf:"varint,33,opt" json:"Timestamp,omitempty"`
	ContentKey       []byte             `protobuf:"bytes,34,opt" json:"ContentKey,omitempty"`
	Owner            []byte             `protobuf:"bytes,35,opt" json:"Owner,omitempty"`
	Src              *string            `protobuf:"bytes,36,opt" json:"Src,omitempty"`
	Path             *string            `protobuf:"bytes,37,opt" json:"Path,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *UpaxClientMsg) Reset()         { *m = UpaxClientMsg{} }
func (m *UpaxClientMsg) String() string { return proto.CompactTextString(m) }
func (*UpaxClientMsg) ProtoMessage()    {}

func (m *UpaxClientMsg) GetOp() UpaxClientMsg_Cmd {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return 0
}

func (m *UpaxClientMsg) GetMsgN() uint64 {
	if m != nil && m.MsgN != nil {
		return *m.MsgN
	}
	return 0
}

func (m *UpaxClientMsg) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *UpaxClientMsg) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *UpaxClientMsg) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *UpaxClientMsg) GetYourSeqN() uint64 {
	if m != nil && m.YourSeqN != nil {
		return *m.YourSeqN
	}
	return 0
}

func (m *UpaxClientMsg) GetYourID() []byte {
	if m != nil {
		return m.YourID
	}
	return nil
}

func (m *UpaxClientMsg) GetErrCode() uint64 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *UpaxClientMsg) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func (m *UpaxClientMsg) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *UpaxClientMsg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpaxClientMsg) GetIndex() int64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *UpaxClientMsg) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *UpaxClientMsg) GetContentKey() []byte {
	if m != nil {
		return m.ContentKey
	}
	return nil
}

func (m *UpaxClientMsg) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *UpaxClientMsg) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *UpaxClientMsg) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func init() {
	proto.RegisterEnum("upax_go.UpaxClientMsg_Cmd", UpaxClientMsg_Cmd_name, UpaxClientMsg_Cmd_value)
}
