// Code generated by protoc-gen-go.
// source: cluster.proto
// DO NOT EDIT!

package upax_go

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type UpaxClusterMsg_Cmd int32

const (
	UpaxClusterMsg_KeepAlive UpaxClusterMsg_Cmd = 3
	UpaxClusterMsg_Ack       UpaxClusterMsg_Cmd = 4
	UpaxClusterMsg_Error     UpaxClusterMsg_Cmd = 5
	UpaxClusterMsg_Get       UpaxClusterMsg_Cmd = 6
	UpaxClusterMsg_Put       UpaxClusterMsg_Cmd = 7
	UpaxClusterMsg_IHave     UpaxClusterMsg_Cmd = 8
	UpaxClusterMsg_LogEntry  UpaxClusterMsg_Cmd = 9
)

var UpaxClusterMsg_Cmd_name = map[int32]string{
	3: "KeepAlive",
	4: "Ack",
	5: "Error",
	6: "Get",
	7: "Put",
	8: "IHave",
	9: "LogEntry",
}
var UpaxClusterMsg_Cmd_value = map[string]int32{
	"KeepAlive": 3,
	"Ack":       4,
	"Error":     5,
	"Get":       6,
	"Put":       7,
	"IHave":     8,
	"LogEntry":  9,
}

func (x UpaxClusterMsg_Cmd) Enum() *UpaxClusterMsg_Cmd {
	p := new(UpaxClusterMsg_Cmd)
	*p = x
	return p
}
func (x UpaxClusterMsg_Cmd) String() string {
	return proto.EnumName(UpaxClusterMsg_Cmd_name, int32(x))
}
func (x UpaxClusterMsg_Cmd) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *UpaxClusterMsg_Cmd) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UpaxClusterMsg_Cmd_value, data, "UpaxClusterMsg_Cmd")
	if err != nil {
		return err
	}
	*x = UpaxClusterMsg_Cmd(value)
	return nil
}

type UpaxClusterMsg struct {
	Op               *UpaxClusterMsg_Cmd `protobuf:"varint,1,opt,enum=upax_go.UpaxClusterMsg_Cmd" json:"Op,omitempty"`
	MsgN             *uint64             `protobuf:"varint,2,opt" json:"MsgN,omitempty"`
	ID               []byte              `protobuf:"bytes,3,opt" json:"ID,omitempty"`
	Sig              []byte              `protobuf:"bytes,5,opt" json:"Sig,omitempty"`
	YourSeqN         *uint64             `protobuf:"varint,6,opt" json:"YourSeqN,omitempty"`
	YourID           []byte              `protobuf:"bytes,7,opt" json:"YourID,omitempty"`
	ErrCode          *uint64             `protobuf:"varint,8,opt" json:"ErrCode,omitempty"`
	ErrDesc          *string             `protobuf:"bytes,9,opt" json:"ErrDesc,omitempty"`
	Hash             []byte              `protobuf:"bytes,10,opt" json:"Hash,omitempty"`
	Payload          []byte              `protobuf:"bytes,11,opt" json:"Payload,omitempty"`
	Index            *int64              `protobuf:"varint,32,opt" json:"Index,omitempty"`
	Timestamp        *int64              `protobuf:"varint,33,opt" json:"Timestamp,omitempty"`
	ContentKey       []byte              `protobuf:"bytes,34,opt" json:"ContentKey,omitempty"`
	Owner            []byte              `protobuf:"bytes,35,opt" json:"Owner,omitempty"`
	Src              *string             `protobuf:"bytes,36,opt" json:"Src,omitempty"`
	Path             *string             `protobuf:"bytes,37,opt" json:"Path,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *UpaxClusterMsg) Reset()         { *m = UpaxClusterMsg{} }
func (m *UpaxClusterMsg) String() string { return proto.CompactTextString(m) }
func (*UpaxClusterMsg) ProtoMessage()    {}

func (m *UpaxClusterMsg) GetOp() UpaxClusterMsg_Cmd {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return 0
}

func (m *UpaxClusterMsg) GetMsgN() uint64 {
	if m != nil && m.MsgN != nil {
		return *m.MsgN
	}
	return 0
}

func (m *UpaxClusterMsg) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *UpaxClusterMsg) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *UpaxClusterMsg) GetYourSeqN() uint64 {
	if m != nil && m.YourSeqN != nil {
		return *m.YourSeqN
	}
	return 0
}

func (m *UpaxClusterMsg) GetYourID() []byte {
	if m != nil {
		return m.YourID
	}
	return nil
}

func (m *UpaxClusterMsg) GetErrCode() uint64 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *UpaxClusterMsg) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func (m *UpaxClusterMsg) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *UpaxClusterMsg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpaxClusterMsg) GetIndex() int64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *UpaxClusterMsg) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *UpaxClusterMsg) GetContentKey() []byte {
	if m != nil {
		return m.ContentKey
	}
	return nil
}

func (m *UpaxClusterMsg) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *UpaxClusterMsg) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *UpaxClusterMsg) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func init() {
	proto.RegisterEnum("upax_go.UpaxClusterMsg_Cmd", UpaxClusterMsg_Cmd_name, UpaxClusterMsg_Cmd_value)
}
