#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/upax_go
  
  rm -rf myApp/* tmp/* 
  
  pySloc -L go cmd/upaxServer/upaxServer.go  -X c.pb.go -X s.pb.go -v $@
else
  echo "DEV_BASE is not defined"
fi
